# ----------- BUILD STAGE -----------

FROM golang:1.25.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bapddang-server

# ----------- RUN STAGE -----------

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /bapddang-server .

EXPOSE 8080

CMD ["./bapddang-server"]